//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDepartMent
    {
        public string FDepartMentId { get; set; }
        public string Companyid { get; set; }
        public string FDepartMentName { get; set; }
        public string FDepartMentLeader { get; set; }
        public string FDepartMentRemark { get; set; }
        public string FDepartMentExtra { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
