//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDepartMent
    {
        public string SDepartMentId { get; set; }
        public string FDepartMentId { get; set; }
        public string SDepartMentName { get; set; }
        public string SDepartMentLeader { get; set; }
        public string SDepartMentRemark { get; set; }
        public string SDepartMentExtra { get; set; }
        public string DepartMentArea { get; set; }
        public string DepartMentPlace { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
