//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CH_Checker
    {
        public string ID { get; set; }
        public string CheckerID { get; set; }
        public string CheckFlowID { get; set; }
        public Nullable<int> lvl1 { get; set; }
        public Nullable<int> lvl2 { get; set; }
    }
}
