//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FD_AccountPayable
    {
        public string ID { get; set; }
        public string ReceivePMNo { get; set; }
        public string SupplierID { get; set; }
        public string ProjectID { get; set; }
        public Nullable<decimal> PayAmount { get; set; }
        public string PayState { get; set; }
        public Nullable<bool> InvoiceState { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Remark { get; set; }
        public string Attachment { get; set; }
        public Nullable<decimal> RealPayAmount { get; set; }
    }
}
