//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FD_AccountReceivable
    {
        public string ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectID { get; set; }
        public string BudgetID { get; set; }
        public string CustomerName { get; set; }
        public string CompletionPercent { get; set; }
        public bool InvoiceOrnot { get; set; }
        public string InvoiceNum { get; set; }
        public string InvoiceType { get; set; }
        public decimal InvoiceAmount { get; set; }
        public decimal BudgetSum { get; set; }
        public decimal HaveReceive { get; set; }
        public Nullable<decimal> RestAmount { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string PaymentState { get; set; }
        public string Remark { get; set; }
        public string AnnetPath { get; set; }
        public Nullable<decimal> RealReceiveAmount { get; set; }
    }
}
