//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GM_PurchaseMaterial
    {
        public string GID { get; set; }
        public string PurchaseMNo { get; set; }
        public string SupplierID { get; set; }
        public string AMGID { get; set; }
        public string ProjectNo { get; set; }
        public string ReceiptMethod { get; set; }
        public string OrderStatu { get; set; }
        public string OrderType { get; set; }
        public string Remark { get; set; }
        public string CheckProcess { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public Nullable<System.DateTime> SupplierAckDate { get; set; }
    }
}
