//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GM_EXWarehouse
    {
        public string EXID { get; set; }
        public System.DateTime EXDate { get; set; }
        public int EXTypeID { get; set; }
        public string ProjectID { get; set; }
        public string Operator { get; set; }
        public System.DateTime OperationTime { get; set; }
        public string OperationListID { get; set; }
        public string RefrenceNo { get; set; }
        public string IMWarehouse { get; set; }
        public string EXWarehouse { get; set; }
    }
}
