//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GM_MaterialStock
    {
        public string ID { get; set; }
        public string MaterialID { get; set; }
        public string WarehouseID { get; set; }
        public decimal CurAmount { get; set; }
        public Nullable<decimal> MinAmount { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public Nullable<decimal> VirtualAmount { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
    }
}
