//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GM_ReceiptMaterial
    {
        public string ReceivePMNo { get; set; }
        public string PMNo { get; set; }
        public string ProjectNo { get; set; }
        public string ReceivingCase { get; set; }
        public string Remark { get; set; }
        public string ConfirmMan { get; set; }
        public Nullable<System.DateTime> ConfirmTime { get; set; }
        public Nullable<decimal> RMTotalPrice { get; set; }
        public string OperationLstId { get; set; }
    }
}
