//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GM_ResidualM
    {
        public string GID { get; set; }
        public string ResidualNo { get; set; }
        public string ProjectNo { get; set; }
        public string AuditProcess { get; set; }
        public Nullable<System.DateTime> BackDate { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string Remark { get; set; }
        public string SupplierID { get; set; }
        public string ResidualType { get; set; }
    }
}
