//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GM_Warehouse
    {
        public string UID { get; set; }
        public string WarehouseID { get; set; }
        public string WarehouseName { get; set; }
        public string Location { get; set; }
        public string Manager { get; set; }
    }
}
