//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GM_SupplierInfo
    {
        public decimal UID { get; set; }
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string Contact { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string InputPerson { get; set; }
        public Nullable<System.DateTime> InputTime { get; set; }
        public string BankAccount { get; set; }
        public string MainProduct { get; set; }
        public string Remark { get; set; }
        public string QualificationPath { get; set; }
        public string QualificationName { get; set; }
        public string BankName { get; set; }
        public string PaymentCycle { get; set; }
        public string Email { get; set; }
        public string Tax { get; set; }
        public string Bank { get; set; }
        public string CompanyProperity { get; set; }
    }
}
