//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GW_CustomRating
    {
        public decimal UID { get; set; }
        public string AppNo { get; set; }
        public Nullable<double> ServiceQuality { get; set; }
        public Nullable<double> ServiceSpeed { get; set; }
        public Nullable<double> ServiceAttitude { get; set; }
        public string ServiceAdvice { get; set; }
        public string Appraiser { get; set; }
        public Nullable<System.DateTime> AppraisTime { get; set; }
    }
}
