//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GW_MarkInfo
    {
        public decimal ID { get; set; }
        public string ProjectNo { get; set; }
        public string WorkPlace { get; set; }
        public Nullable<double> Xaxes { get; set; }
        public Nullable<double> Yaxes { get; set; }
        public string IsHandled { get; set; }
        public string HandlePicPath { get; set; }
        public string HandleDes { get; set; }
        public string WarnLevel { get; set; }
        public string Mark { get; set; }
        public string ExceptionDes { get; set; }
        public string ExceptionHandleSug { get; set; }
        public string ExcPicPath { get; set; }
        public string AuditMethod { get; set; }
        public string AuditResult { get; set; }
        public string Remark { get; set; }
        public string ReportMan { get; set; }
        public Nullable<System.DateTime> ReportTime { get; set; }
        public string HandleMan { get; set; }
        public Nullable<System.DateTime> HandleTime { get; set; }
        public string AuditMan { get; set; }
        public Nullable<System.DateTime> AuditTime { get; set; }
    }
}
