//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GW_FieldSchedule
    {
        public string ProjectNo { get; set; }
        public Nullable<System.DateTime> ProStartPlanTime { get; set; }
        public Nullable<System.DateTime> ProStartRealTime { get; set; }
        public Nullable<System.DateTime> ProHalfPlanTime { get; set; }
        public Nullable<System.DateTime> ProHalfRealTime { get; set; }
        public Nullable<System.DateTime> ProEndPlanTime { get; set; }
        public Nullable<System.DateTime> ProEndRealTime { get; set; }
        public Nullable<System.DateTime> ProAcceptPlanTime { get; set; }
        public Nullable<System.DateTime> ProAcceptRealTime { get; set; }
        public Nullable<System.DateTime> ProWarePlanTime { get; set; }
        public Nullable<System.DateTime> ProWareRealTime { get; set; }
        public string ProProcess { get; set; }
        public string InputMan { get; set; }
        public Nullable<System.DateTime> InputTime { get; set; }
        public Nullable<bool> Stopped { get; set; }
    }
}
