//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_GW_FieldInfoManagement
    {
        public decimal ID { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public string FieldName { get; set; }
        public string FieldPrincipal { get; set; }
        public string FieldMapName { get; set; }
        public string FieldMapPath { get; set; }
        public string Remark { get; set; }
        public Nullable<double> CustomRating { get; set; }
        public string InputMan { get; set; }
        public Nullable<System.DateTime> InputTime { get; set; }
        public string WarehouseID { get; set; }
    }
}
