//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HR_SchList
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string AMClassGoOn { get; set; }
        public string ACGST { get; set; }
        public string ACGET { get; set; }
        public string AMClassOff { get; set; }
        public string ACOST { get; set; }
        public string ACOET { get; set; }
        public string PMClassGoOn { get; set; }
        public string PCGST { get; set; }
        public string PCGET { get; set; }
        public string PMClassOff { get; set; }
        public string PCOST { get; set; }
        public string PCOET { get; set; }
        public Nullable<bool> Two { get; set; }
        public Nullable<bool> Four { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EditorName { get; set; }
        public Nullable<System.DateTime> EditeTime { get; set; }
    }
}
