//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HR_StaffSalary
    {
        public string ID { get; set; }
        public string StaffID { get; set; }
        public Nullable<decimal> DaySalary { get; set; }
        public Nullable<decimal> EHS { get; set; }
        public Nullable<decimal> Food { get; set; }
        public Nullable<decimal> Connection { get; set; }
        public Nullable<decimal> Water { get; set; }
        public Nullable<decimal> EWSalary { get; set; }
        public Nullable<decimal> DHours { get; set; }
        public Nullable<decimal> EHours { get; set; }
        public Nullable<decimal> DaySalarySum { get; set; }
        public Nullable<decimal> EWSalarySum { get; set; }
        public Nullable<decimal> ConnectionSum { get; set; }
        public Nullable<decimal> WaterSum { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
    }
}
