//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HR_Staff
    {
        public string StaffID { get; set; }
        public string Name { get; set; }
        public string TelNum { get; set; }
        public string Urgencyperson { get; set; }
        public string UPTelNum { get; set; }
        public string Email { get; set; }
        public string Nation { get; set; }
        public string HireState { get; set; }
        public string CertificateType { get; set; }
        public string CertificateNum { get; set; }
        public string IdCardAddress { get; set; }
        public string Nativeplace { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Sex { get; set; }
        public string MaritalStatus { get; set; }
        public string StaffType { get; set; }
        public string WorkAddress { get; set; }
        public string Area { get; set; }
        public string BankAccount { get; set; }
        public string BankType { get; set; }
        public string Craft { get; set; }
        public string Education { get; set; }
        public string GraduationSchool { get; set; }
        public string Major { get; set; }
        public string Remark { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EditorName { get; set; }
        public Nullable<System.DateTime> EditeTime { get; set; }
        public string ID1 { get; set; }
        public string ID2 { get; set; }
        public string ID3 { get; set; }
        public string ID4 { get; set; }
        public string ID5 { get; set; }
        public string Department { get; set; }
        public string ImagePath { get; set; }
        public string SocialInsuranceType { get; set; }
        public Nullable<System.DateTime> SSStartdate { get; set; }
        public Nullable<System.DateTime> SSEnddate { get; set; }
        public string NoAttend { get; set; }
        public Nullable<System.DateTime> PreDimissionDate { get; set; }
        public string DimissionType { get; set; }
        public string DimissionReason { get; set; }
        public Nullable<int> Probation { get; set; }
        public Nullable<System.DateTime> ProbationDate { get; set; }
        public Nullable<bool> ProbationValid { get; set; }
        public Nullable<bool> FundValid { get; set; }
    }
}
