//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HR_SalaryInput
    {
        public string ID { get; set; }
        public string StaffID { get; set; }
        public string Name { get; set; }
        public string Job { get; set; }
        public Nullable<System.DateTime> EPDate { get; set; }
        public Nullable<System.DateTime> DDate { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> WorkBenefit { get; set; }
        public Nullable<decimal> FoodBasic { get; set; }
        public Nullable<decimal> ConnectionBasic { get; set; }
        public Nullable<decimal> ComputerBasic { get; set; }
        public Nullable<decimal> DayNum { get; set; }
        public Nullable<decimal> VacationWithSalary { get; set; }
        public Nullable<decimal> DaysOff { get; set; }
        public Nullable<decimal> BTDays { get; set; }
        public Nullable<decimal> VacationNoSalary { get; set; }
        public Nullable<decimal> NoWork { get; set; }
        public Nullable<decimal> PayBasciSalary { get; set; }
        public Nullable<decimal> PayWorkBenefit { get; set; }
        public Nullable<decimal> PayFoodCurrentMonth { get; set; }
        public Nullable<decimal> PayFoodNextMonth { get; set; }
        public Nullable<decimal> PayBTFood { get; set; }
        public Nullable<decimal> PayConnection { get; set; }
        public Nullable<decimal> PayComputer { get; set; }
        public Nullable<decimal> PayFoodDifference { get; set; }
        public Nullable<decimal> PayBuLastMonth { get; set; }
        public Nullable<decimal> PaySum { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
