//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HR_WorkTime
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string AMClassGoOn { get; set; }
        public string EarlistTimeACG { get; set; }
        public string AMClassOff { get; set; }
        public string LatestTimeACO { get; set; }
        public string PMClassGoOn { get; set; }
        public string EarlistTimePCG { get; set; }
        public string PMClassOff { get; set; }
        public string LatestTimePCO { get; set; }
        public string Remark { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EditorName { get; set; }
        public Nullable<System.DateTime> EditeTime { get; set; }
    }
}
