//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PE_Users
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserDspName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string MobilePhone { get; set; }
        public string OfficePhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string Address { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<bool> Activity { get; set; }
        public string UserType { get; set; }
        public string DeptID { get; set; }
        public string DeptName { get; set; }
        public string CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Style { get; set; }
        public string Creator { get; set; }
        public string CreatorID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Editor { get; set; }
        public string EditorID { get; set; }
        public Nullable<System.DateTime> EditeTime { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string LastMacAddress { get; set; }
        public string CurrentLoginIP { get; set; }
        public Nullable<System.DateTime> CurrentLoginTime { get; set; }
        public string CurrentMacAddress { get; set; }
        public Nullable<System.DateTime> LastPasswordTime { get; set; }
        public string Name { get; set; }
        public string UserImage { get; set; }
        public Nullable<bool> SendEmailMsg { get; set; }
    }
}
