//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PE_Menu
    {
        public string MenuID { get; set; }
        public string ParentID { get; set; }
        public string TextCN { get; set; }
        public string TextEN { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string URL { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Creator { get; set; }
        public string CreatorID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Editor { get; set; }
        public string EditorID { get; set; }
        public Nullable<System.DateTime> EditeTime { get; set; }
        public Nullable<bool> DefaultURL { get; set; }
    }
}
