//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PM_SupplierMaterialExtra
    {
        public string SupplierMaterialNo { get; set; }
        public string MaterialNo { get; set; }
        public string MaterialName { get; set; }
        public string Size { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<double> ApplyNumber { get; set; }
        public Nullable<double> ActualNumber { get; set; }
        public string Extra { get; set; }
        public string SupplierOrderID { get; set; }
        public string ApplyMaterialID { get; set; }
    }
}
