//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PM_SupplierOrderExtra
    {
        public string SupplierOrderNo { get; set; }
        public string MakeMan { get; set; }
        public Nullable<System.DateTime> MakeDate { get; set; }
        public string CheckMan { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string CheckStatus { get; set; }
        public string Extra { get; set; }
    }
}
