//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PM_OrderInfo
    {
        public string CompanyOrderNo { get; set; }
        public string OrderMan { get; set; }
        public string ProjectName { get; set; }
        public string ClientOrderNo { get; set; }
        public string ClientName { get; set; }
        public Nullable<decimal> OrderMoney { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        public Nullable<System.DateTime> ActualStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public Nullable<System.DateTime> ActualEndDate { get; set; }
        public string BoolStorage { get; set; }
        public string BoolCheck { get; set; }
        public string BoolInvoice { get; set; }
        public string Extra { get; set; }
        public string BoolTax { get; set; }
        public string TaxRate { get; set; }
        public string PayCondition { get; set; }
        public string ReviewMan { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string AgentMan { get; set; }
        public Nullable<System.DateTime> AgentDate { get; set; }
    }
}
