//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PM_ProjectMaterialApply
    {
        public string MaterialApplyNo { get; set; }
        public string PoNo { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public string WorkSite { get; set; }
        public string ApplyMan { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public string Tel { get; set; }
        public string Extra { get; set; }
        public string CheckStatusEngineeringDepartment { get; set; }
        public string CheckManEngineeringDepartment { get; set; }
        public Nullable<System.DateTime> CheckDateEngineeringDepartment { get; set; }
        public string ConfirmStatus { get; set; }
        public string ConfirmMan { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
    }
}
