//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_US_Message
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Url { get; set; }
        public bool Sent { get; set; }
        public string EmployeeID { get; set; }
        public string Type { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Solved { get; set; }
        public Nullable<bool> NewWindow { get; set; }
    }
}
