//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CH_TaskFunc
    {
        public string Name { get; set; }
        public string ID { get; set; }
        public string StaffID { get; set; }
        public string MenuID { get; set; }
        public string Url { get; set; }
        public int State { get; set; }
        public System.DateTime EndTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string OperationID { get; set; }
        public string Description { get; set; }
        public bool Expire { get; set; }
    }
}
