//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GM_MApply
    {
        public string IsEnableNo { get; set; }
        public string ApplyMaterialNo { get; set; }
        public string CheckProcess { get; set; }
        public string ApplyMState { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public string Name { get; set; }
        public string GID { get; set; }
        public string ApplyMan { get; set; }
        public Nullable<System.DateTime> PrepaidDay { get; set; }
        public string Tel { get; set; }
        public string ProjectNo { get; set; }
        public string FieldName { get; set; }
        public string FPMGID { get; set; }
    }
}
