//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GM_DetailBudget
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public string QuotationNo { get; set; }
        public string AuditProgress { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public string BudgetStatus { get; set; }
        public Nullable<System.DateTime> OfferDate { get; set; }
        public decimal OfferMoney { get; set; }
        public Nullable<decimal> CostMoney { get; set; }
        public Nullable<decimal> MaterialOffer { get; set; }
        public Nullable<decimal> LaborOffer { get; set; }
        public Nullable<decimal> MaterialCost { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public Nullable<decimal> OtherFeeOffer { get; set; }
        public Nullable<decimal> OtherFeeCost { get; set; }
        public string TaxRate { get; set; }
        public string Extra { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<System.DateTime> AgentDate { get; set; }
        public string AgentMan { get; set; }
        public string GID { get; set; }
        public string ClientName { get; set; }
        public Nullable<int> Version { get; set; }
        public string RateMargin { get; set; }
        public string NetMargin { get; set; }
    }
}
