//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GM_DetailMStock
    {
        public string ID { get; set; }
        public string WarehouseID { get; set; }
        public decimal CurAmount { get; set; }
        public Nullable<decimal> MinAmount { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public string MaterialID { get; set; }
        public string MaterialName { get; set; }
        public string PicturePath { get; set; }
        public string Size { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Brand { get; set; }
        public string PurchaseCycle { get; set; }
        public string MinPurchase { get; set; }
        public string WarehouseName { get; set; }
        public string Location { get; set; }
        public string Manager { get; set; }
        public Nullable<decimal> VirtualAmount { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
    }
}
