//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GM_EXDetail
    {
        public string CheckStateDsp { get; set; }
        public string OperationListID { get; set; }
        public string EXID { get; set; }
        public System.DateTime EXDate { get; set; }
        public int EXTypeID { get; set; }
        public string ProjectID { get; set; }
        public string Operator { get; set; }
        public System.DateTime OperationTime { get; set; }
        public string RefrenceNo { get; set; }
        public string EXType { get; set; }
        public Nullable<int> State { get; set; }
        public string IMWarehouse { get; set; }
        public string EXWarehouse { get; set; }
        public string NO { get; set; }
        public Nullable<decimal> Num { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string MaterialName { get; set; }
        public string Size { get; set; }
        public string Unit { get; set; }
        public string MaterialID { get; set; }
        public string IsEnableNo { get; set; }
        public string Type { get; set; }
        public string Remark { get; set; }
        public decimal UID { get; set; }
        public string morfa { get; set; }
        public string Brand { get; set; }
        public string PicturePath { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string PurchaseCycle { get; set; }
        public string MinPurchase { get; set; }
    }
}
