//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GM_FAApply
    {
        public string GID { get; set; }
        public string ApplyNo { get; set; }
        public string Applicant { get; set; }
        public string ApplicantSector { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> No_Date { get; set; }
        public string AuditProcess { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> OperateTime { get; set; }
        public string Remark { get; set; }
        public string Operator { get; set; }
    }
}
