//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HR_PuchedException
    {
        public string Name { get; set; }
        public string ID { get; set; }
        public string UserId { get; set; }
        public System.DateTime AttendTime { get; set; }
        public string EditUserId { get; set; }
        public Nullable<System.DateTime> EditTime { get; set; }
        public int PunchedOrder { get; set; }
        public int State { get; set; }
        public bool Solved { get; set; }
        public string StateName { get; set; }
    }
}
