//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HR_StaffJobWithName
    {
        public string StaffID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public string StaffType { get; set; }
        public string JobID { get; set; }
        public string JobName { get; set; }
        public string DutyID { get; set; }
        public string DutyName { get; set; }
        public string DutyType { get; set; }
        public string PositionCategoryID { get; set; }
        public string PositionCategoryName { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<System.DateTime> ValidTime { get; set; }
        public string ChangeType { get; set; }
        public string Remark { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EditorName { get; set; }
        public Nullable<System.DateTime> EditeTime { get; set; }
        public string StaffJobID { get; set; }
    }
}
