//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HR_Job
    {
        public string JobID { get; set; }
        public string JobName { get; set; }
        public string DutyID { get; set; }
        public string DutyName { get; set; }
        public string DutyType { get; set; }
        public string PositionCategoryID { get; set; }
        public string PositionCategoryName { get; set; }
    }
}
