//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HR_IDNameWithDepName
    {
        public string StaffID { get; set; }
        public string Name { get; set; }
        public string ID1 { get; set; }
        public string Department1No { get; set; }
        public string Department1Name { get; set; }
        public string ID2 { get; set; }
        public string Department2No { get; set; }
        public string Department2Name { get; set; }
        public string ID3 { get; set; }
        public string Department3No { get; set; }
        public string Department3Name { get; set; }
        public string ID4 { get; set; }
        public string Department4No { get; set; }
        public string Department4Name { get; set; }
        public string ID5 { get; set; }
        public string Department5No { get; set; }
        public string Department5Name { get; set; }
        public string Department { get; set; }
        public string HireState { get; set; }
    }
}
