//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HR_VacationWithDepName
    {
        public string ID { get; set; }
        public string StaffID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string VPType { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<decimal> TimeSpan { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string VPReason { get; set; }
        public string Remark { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EditorName { get; set; }
        public Nullable<System.DateTime> EditeTime { get; set; }
        public string OperationListID { get; set; }
        public string LastID { get; set; }
        public Nullable<bool> VPEdit { get; set; }
        public Nullable<bool> VPDelete { get; set; }
        public string EditOrDelete { get; set; }
    }
}
