//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HR_WorkOverTime
    {
        public string ID { get; set; }
        public string StaffID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> LastYear { get; set; }
        public Nullable<decimal> CurrentYearSum { get; set; }
        public Nullable<decimal> CurrentYear { get; set; }
        public Nullable<decimal> Personal { get; set; }
        public Nullable<decimal> Company { get; set; }
        public Nullable<decimal> CurrentYearLast { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string Remark { get; set; }
        public string CreaterName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string EditorName { get; set; }
        public Nullable<System.DateTime> EditeTime { get; set; }
    }
}
