//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PE_RolePermission
    {
        public string TextCN { get; set; }
        public string TextEN { get; set; }
        public string ParentID { get; set; }
        public string URL { get; set; }
        public Nullable<bool> Visible { get; set; }
        public string Action { get; set; }
        public string Description { get; set; }
        public string RoleID { get; set; }
        public string MenuID { get; set; }
    }
}
