//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeerInformation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_US_WorkReportWithHours
    {
        public string ProjectID { get; set; }
        public string ProjectNo { get; set; }
        public string ProjectName { get; set; }
        public string ProjectSite { get; set; }
        public System.DateTime Date { get; set; }
        public string OperationID { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string AttachFile { get; set; }
        public int ProgressPercentage { get; set; }
        public string Remark { get; set; }
        public string ID { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public decimal ExtraHours { get; set; }
        public decimal DutyHours { get; set; }
    }
}
